language: r
cache: packages
warnings_are_errors: true
r:
  - oldrel
  - release
  - devel

bioc_packages:
  - BiocInstaller
  - BiocCheck

after_success:
  - R CMD BiocCheck --new-package --no-check-vignettes ploidyverse*.tar.gz

notifications:
  email: false
